### ISSUE TITLE
import failing || optimix 

### ISSUE THREAD

**Issue by complexgenome** [limix/limix-lmm#14]
This is related to optimix import that fails. 

 python -c "import optimix; optimix.test()"
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ss5505/conda/my-envs/python3/lib/python3.5/site-packages/optimix/__init__.py", line 5, in <module>
    from ._function import Function
  File "/home/ss5505/conda/my-envs/python3/lib/python3.5/site-packages/optimix/_function.py", line 177
    named_vars[f"{self._name}[{i}]"] = f._variables
                                  ^
SyntaxError: invalid syntax`

I'm on unix, conda (v4.8.2), Python (v3.5.5). optimix-3.0.3 
I installed optimix using pip, uninstalled and again tried. Still import fails. This is limiting me to use `glimix-core`
@horta Sorry, don't know where else to raise this issue.

**Comment by horta** [comment]
Hi @sariya . You need to use Python >=3.6.
Python 3.5 is not supported...
